name: Android APK erstellen

on: 
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: .NET 10 installieren
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: MAUI Workload installieren
        run: dotnet workload install maui

      - name: App zu APK bauen
        run: dotnet publish OmniApp/OmniApp.csproj -f net10.0-android -c Release -p:AndroidPackageFormat=apk -p:AndroidKeyStore=false

      - name: APK zum Download bereitstellen
        uses: actions/upload-artifact@v4
        with:
          name: MeinOmniCalculator
          path: OmniApp/bin/Release/net10.0-android/*-Signed.apk
